### ISSUE TITLE
WindowsAzure.MobileServices.SQLiteStore Debug and Release behavior different for insert, update and push

### ISSUE THREAD

**Issue by Invoice360** [Azure/azure-mobile-services#890] opened 2016-04-29 02:24 UTC
I have this project that inserts into the SQLiteStore followed by an update before a push to the server. I noticed the behvaior to be different when I compile in debug vs release mode. In debug mode, it appears to be working correctly (at least for me :)), the updated record gets pushed to the server. In release mode, after the update the record is never pushed to the server. The following is my sample code in a UWP app.

    public class SimpleObject
    {
        public SimpleObject()
        {
        }
        public string Id { get; set; }

        [Version]
        public string Version { get; set; }

        public string Name { get; set; }
    }

    private async void Button_Tapped(object sender, TappedRoutedEventArgs e)
        {
            MobileServiceClient mservice = new MobileServiceClient("http://localhost:8571");
            if (!mservice.SyncContext.IsInitialized)
            {
                var store = new MobileServiceSQLiteStore("localsync.db");
                store.DefineTable<SimpleObject>();
                await mservice.SyncContext.InitializeAsync(store);
                IMobileServiceSyncTable<SimpleObject> simpleTableSL = mservice.GetSyncTable<SimpleObject>();
                SimpleObject ivp = new SimpleObject();
                ivp.Name = "testInsert";
                await simpleTableSL.InsertAsync(ivp);
                ivp.Name = "testUpdate";
                await simpleTableSL.UpdateAsync(ivp);
                System.Diagnostics.Debug.WriteLine(mservice.SyncContext.PendingOperations.ToString());
                await mservice.SyncContext.PushAsync(); 
            }
        }

Digging around a litte more into the sqlite .db file. I noticed the differences in the operations table after the update.
In release mode the sequence becomes "0" (second last field)

Release Mode
sqlite> select * from __operations;
850a9c1d-a237-485a-9ae2-933e93f49738|0|0|SimpleObject|0|e5148a4e-53d9-496c-89a9-954a1e7601c8|||0|1

Debug Mode
sqlite> select * from __operations;
cac1b7a7-1452-493d-b56e-6af556d5be6a|0|2|InventoryProduct|0|39be8cce-f71a-48f6-b7b3-a846fd781b83|||1|2

It appears to occur after VS2015 update 2. I happen to have a machine that has not applied VS2015 update 2. In that version,
the release and debug mode gives the same result.

Other details
VS Professional 2015 Update 2 (Windows 10 Home 1511 10586.218)
or
VS15 Preview (Windows 10 Pro Insider Preview 1511 14295.1005)

WindowsAzure.MobileServices.SQLiteStore 1.0.4

Is this a bug or am I missing something?  

Thanks for reading this and have a nice day.

**Comment by shrishrirang** [comment] 2016-04-29 21:03
Thanks for the investigation @Invoice360 The last column is the version column which is incremented every time the record is edited. It looks like the .db file in release mode does not have the new version value.

Is there a difference in the SimpleObject table in the .db file in release and debug modes? 

I am wondering if not disposing the SQLite connection could be causing some updates to be held in memory. Can you try initializing mservice in a `using` block?

**Comment by Invoice360** [comment] 2016-04-30 08:39
Hi @shrishrirang,

Thanks for your reply. The SimpleObject table is the same (both become "testUpdate") 
after the updateasync in both release and debug mode. The version in the operations table did not become "2" as you have noted in the release version. And the sequence becomes "0". I have tried with the using block for mservice, it will still give us different result in the operations table in debug vs release,
which affects the push.

**Comment by shrishrirang** [comment] 2016-05-03 03:53
That is weird, I don't see a reason why that should happen. Are you saying that with the configuration you mentioned, UpdateAsync is completely broken? Or do you run into it only in specific scenarios?

**Comment by Invoice360** [comment] 2016-05-04 08:28
Somehow with the following configurations I am having issues with  InsertAsync (no push) followed by UpdateAsync as in the demo code above.

Visual Studio 2015 Update 2 or Visual Studio 15.0.25123.0 PREVIEW 
WindowsAzure.MobileServices.SQLiteStore v1.0.4
SQLite for Universal Windows Platform (SQLite.UWP.2015, Version 3.12.2)
UWP app Compile to Release (x86/x64)

I tested other configurations.
e.g 
VS2015 Update 1 Debug or Release.
or VS2015 Update 2 Debug.
or VS15 PREVIEW Debug.
In these, the version number in the operations table gets updated.

My apologies in advance if I am missing something.

**Comment by Invoice360** [comment] 2016-05-12 02:35
Hi,

This is what I found. 

UWP App MainPage (Compiled to Release VS2015Up2)
InsertAsync (no push)
UpdateAsync
->
.
.
MobileServiceSyncContext
{
ExecuteOperationAsync(MobileServiceTableOperation operation, JObject item)
->ExecuteOperationSafeAsync(operation.ItemId, operation.TableName, async () =>            
-->MobileServiceTableOperation existing = await this.opQueue.GetOperationByItemIdAsync
--->MobileServiceTableOperation.Deserialize
---->operation.Sequence = obj.Value<long?>("sequence").GetValueOrDefault();
 
is returning 0 
}

//Newtonsoft
//Extensions.Convert<JToken, T>(token);
//token becomes null

**Comment by Invoice360** [comment] 2016-05-12 06:24
Hi all,
    Upon further investigation. It looks like a compiler issue caused by the .Net Native tool Chain.

**Comment by tobber72** [comment] 2016-06-28 18:12
Hi.

We have the same problems and we have also tested with Visual Studio Update 3, but unfortunately, the problem remains in that version.

However, we have noticed that if we set "Optimize code" = false the offline functionality works, but then we instead get the following errors when WACK tests have been completed.

"AppName" takes a dependency on Microsoft .Net Native Framework Package 1.x framework but is missing the framework dependency declaration in the manifest.

and

API CoCreateInstance in api-ms-win-core-com-l1-1-0.dll is not supported for this application type. "AppName.dll" calls this API.

If anyone has a solution for this, we would be very grateful!

**Comment by MattWhilden** [comment] 2016-06-30 20:18
I work on the .NET Native runtime and compiler team. I think that @tobber72 has reached out to us via email and we're working with him to investigate this issue. We'll update the issue here as we know more. At first read, this seems like a compiler issue but we won't know until we get more information.

**Comment by MattWhilden** [comment] 2016-07-02 00:34
I've reproduced the issue and began poking around. It's definitely an issue with one of the optimization phases of the compiler. We have some decent strategies for hunting that down and the workarounds for those kinds of bugs aren't usually too onerous. I'll be picking this back up on Tuesday as there's a holiday weekend here in the states.

**Comment by MattWhilden** [comment] 2016-07-05 21:35
@tobber72 reports that he they have worked around this issue by adding this to Properties\Default.rd.xml file:
`<Library Name="Newtonsoft.Json">
     <Assembly
     Name="Newtonsoft.Json"
     DoNotOptimize="true"
     DoNotInline="true" />
   </Library>​`

This instructs the optimizer to ignore all of the types/methods inside of Newtonsoft.Json. This may be an acceptable workaround for some. We're still chasing down exactly which method/methods is being improperly handled.

**Comment by shrishrirang** [comment] 2016-07-05 22:01
Great! Thanks for the update @MattWhilden.

**Comment by MattWhilden** [comment] 2016-07-05 22:08
Yep. Let me know if that doesn't work out for other folks. It's always possible there's more than one issue lurking about. We'll report back when we have something more targeted.

**Comment by adrianhall** [comment] 2016-08-16 21:04
Based on comments, this is not an issue with Azure Mobile Services - closing.

**Closed by adrianhall** 2016-08-16 21:04 UTC
