### ISSUE TITLE
Xamarin.Android crash during UpdateAsync

### ISSUE THREAD

**Issue by iitr-ankur** [Azure/azure-mobile-services#688] opened 2015-04-29 10:23 UTC
Hi,
My application is crashing even though I am using a try-catch block as below:
 try
                {
                    await Constants.MessagesRepo.UpdateAsync(currentMsg);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(Thread.CurrentThread.ManagedThreadId + " Exception: " + ex);
                }

The crash doesn't happen always and I suspect it might be happening when multiple threads are updating the local db. 

Stacktrace:
04-29 15:10:10.376  5989  6009 E mono-rt :   at <unknown> <0xffffffff>
04-29 15:10:10.376  5989  6009 E mono-rt :   at (wrapper managed-to-native) SQLitePCL.SQLite3Provider/NativeMethods.sqlite3_step (intptr) <0xffffffff>
04-29 15:10:10.376  5989  6009 E mono-rt :   at SQLitePCL.SQLite3Provider.SQLitePCL.ISQLite3Provider.Sqlite3Step (intptr) <0x00013>
04-29 15:10:10.376  5989  6009 E mono-rt :   at SQLitePCL.SQLiteStatement.Step () <0x0001d>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.ExecuteNonQuery (string,System.Collections.Generic.IDictionary`2<string, object>) <0x00113>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.UpsertAsyncInternal (string,System.Collections.Generic.IEnumerable`1<Newtonsoft.Json.Linq.JObject>,bool) <0x00327>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.SQLiteStore.MobileServiceSQLiteStore.UpsertAsync (string,System.Collections.Generic.IEnumerable`1<Newtonsoft.Json.Linq.JObject>,bool) <0x0003b>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceLocalStoreExtensions.UpsertAsync (Microsoft.WindowsAzure.MobileServices.Sync.IMobileServiceLocalStore,string,Newtonsoft.Json.Linq.JObject,bool) <0x00051>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.UpdateOperation.ExecuteLocalAsync (Microsoft.WindowsAzure.MobileServices.Sync.IMobileServiceLocalStore,Newtonsoft.Json.Linq.JObject) <0x0001b>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<>c__DisplayClass5b/<<ExecuteOperationAsync>b__5a>d__5d.MoveNext () <0x002bd>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<>c__DisplayClass5b/<<ExecuteOperationAsync>b__5a>d__5d> (Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<>c__DisplayClass5b/<<ExecuteOperationAsync>b__5a>d__5d&) <0x00057>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<>c__DisplayClass5b.<ExecuteOperationAsync>b__5a () <0x000e3>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<ExecuteOperationSafeAsync>d__63.MoveNext () <0x0078f>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<ExecuteOperationSafeAsync>d__63> (Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<ExecuteOperationSafeAsync>d__63&) <0x00057>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.ExecuteOperationSafeAsync (string,string,System.Func`1<System.Threading.Tasks.Task>) <0x0016b>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.ExecuteOperationAsync (Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceTableOperation,Newtonsoft.Json.Linq.JObject) <0x0012b>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<UpdateAsync>d__14.MoveNext () <0x002c3>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<UpdateAsync>d__14> (Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext/<UpdateAsync>d__14&) <0x00057>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.UpdateAsync (string,Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceTableKind,string,Newtonsoft.Json.Linq.JObject) <0x00173>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable/<UpdateAsync>d__4.MoveNext () <0x00103>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start<Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable/<UpdateAsync>d__4> (Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable/<UpdateAsync>d__4&) <0x00057>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable.UpdateAsync (Newtonsoft.Json.Linq.JObject) <0x00113>
04-29 15:10:10.376  5989  6009 E mono-rt :   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncTable`1.UpdateAsync (T) <0x00067>
04-29 15:10:10.376  5989  6009 E mono-rt :   at SchoolApp.Droid.PubDroid/<AddNewMessage>d__2d.MoveNext () <0x003b2>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1<bool>.Start<SchoolApp.Droid.PubDroid/<AddNewMessage>d__2d> (SchoolApp.Droid.PubDroid/<AddNewMessage>d__2d&) <0x00057>
04-29 15:10:10.376  5989  6009 E mono-rt :   at SchoolApp.Droid.PubDroid.AddNewMessage (SchoolApp.Message) <0x00113>
04-29 15:10:10.376  5989  6009 E mono-rt :   at SchoolApp.Droid.PubDroid/<HandleNewMessage>d__28.MoveNext () <0x001c7>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start<SchoolApp.Droid.PubDroid/<HandleNewMessage>d__28> (SchoolApp.Droid.PubDroid/<HandleNewMessage>d__28&) <0x00057>
04-29 15:10:10.376  5989  6009 E mono-rt :   at SchoolApp.Droid.PubDroid.HandleNewMessage (string) <0x00113>
04-29 15:10:10.376  5989  6009 E mono-rt :   at PubNubMessaging.Core.PubnubCore.JsonResponseToCallback<T> (object,System.Action`1<T>) <0x00086>
04-29 15:10:10.376  5989  6009 E mono-rt :   at PubNubMessaging.Core.PubnubCore.GoToCallback (object,System.Action`1<string>) <0x0002b>
04-29 15:10:10.376  5989  6009 E mono-rt :   at PubNubMessaging.Core.PubnubCore.ResponseToUserCallback<T> (System.Collections.Generic.List`1<object>,PubNubMessaging.Core.ResponseType,string[],System.Action`1<T>) <0x0087f>
04-29 15:10:10.376  5989  6009 E mono-rt :   at PubNubMessaging.Core.PubnubCore.ProcessResponseCallbacks<T> (System.Collections.Generic.List`1<object>,PubNubMessaging.Core.RequestState`1<T>) <0x000d3>
04-29 15:10:10.376  5989  6009 E mono-rt :   at PubNubMessaging.Core.PubnubXamarinAndroid.UrlProcessResponseCallback<T> (System.IAsyncResult) <0x00f8f>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Net.SimpleAsyncResult/<SimpleAsyncResult>c__AnonStorey0.<>m__0 (System.Net.SimpleAsyncResult) <0x00023>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Net.SimpleAsyncResult.DoCallback_internal () <0x0002a>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Net.WebAsyncResult.DoCallback () <0x00013>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData) <0x0056b>
04-29 15:10:10.376  5989  6009 E mono-rt :   at (wrapper remoting-invoke-with-check) System.Net.HttpWebRequest.SetResponseData (System.Net.WebConnectionData) <0xffffffff>
04-29 15:10:10.376  5989  6009 E mono-rt :   at System.Net.WebConnection.ReadDone (System.IAsyncResult) <0x009cb>
04-29 15:10:10.376  5989  6009 E mono-rt :   at (wrapper runtime-invoke) <Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr) <0xffffffff>
04-29 15:10:10.376  5989  6009 E mono-rt : 
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
04-29 15:10:10.376  5989  6009 F libc    : Fatal signal 11 (SIGSEGV) at 0x0000000c (code=1), thread 6009 (Threadpool work)

**Comment by iitr-ankur** [comment] 2015-06-22 07:48
@carlosfigueira , @lindydonna , @phvannor , @hasankhan , 

Any update on this? This is a serious Crash issue and there has been no response since last 2 months!!! Does anyone even looks into these issues?

**Comment by hasankhan** [comment] 2015-06-22 18:10
Is it possible for you to log the object being inserted for the failed call?

**Comment by iitr-ankur** [comment] 2015-06-24 05:52
The object being inserted is different every time. Also, I don't see how that will help in anyway. I believe it is because of using multiple threads. I have now added AsyncLock and haven't seen the issue repro(though not much testing done), but I would prefer if this(parallel threads causing crash) is investigated or atleast if there are some guidelines regarding multithreading/parallelism when using the SDK. Either the SDK handles it itself or there should be some guidance on how we should use it in such cases.

**Comment by lindydonna** [comment] 2015-06-24 17:41
@iitr-ankur, we are investigating, but these kinds of multithreaded issues are notoriously hard to reproduce. From what you're describing, I suspect a bug in the SDK.

Could you please help us find the root cause?

    - What threads are the calling UpdateAsync?
    - Where did you add AsyncLock?
    - Can you log the objects being inserted?
    - Could you please provide the exact NuGet versions you are using?  
    - What version of Android are you running on?  Emulator or physical device?

**Comment by iitr-ankur** [comment] 2015-06-25 05:41
These are the links I used for AsyncLock code:
http://stackoverflow.com/questions/24186577/what-is-the-correct-usage-for-sqlite-on-locking-or-async
http://stackoverflow.com/questions/21011179/how-to-protect-resources-that-may-be-used-in-a-multi-threaded-or-async-environme/21011273#21011273
http://blogs.msdn.com/b/pfxteam/archive/2012/02/12/10266988.aspx
I added the AsyncLock in the repository. All my db operations are now encapsulated in the following using block:

Sample usage: 
using(await locker.LockAsync()){
					await SyncTable.UpdateAsync(item);
				}

I had created multiple threads using ThreadPool.QueueUserWorkItem() which are calling this.

Nuget Package details:
  <package id="WindowsAzure.MobileServices" version="1.3.2" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="WindowsAzure.MobileServices.SQLiteStore" version="1.0.4" targetFramework="portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />
  <package id="WindowsAzure.Storage" version="4.4.0-preview" targetFramework="portable-net45+win+MonoAndroid10+xamarinios10+MonoTouch10" />

I am using Moto G 2nd Gen(Android API 21) & Geny Motion Emulator (API 18). I was getting this issue in both.

**Comment by lindydonna** [comment] 2015-06-25 22:04
Thanks for the details. To clarify before your fix, did you explicitly use QueueUserWorkItem using the threadpool, or just call async methods directly?

Can you share any code snippets so that we can try to reproduce?  I'm trying to figure out if there was a concurrency issue between multiple individual async calls or a group of async calls that needed a lock.

**Comment by iitr-ankur** [comment] 2015-06-26 06:36
Most of the async update method calls should be from threads started using QueueUserWorkItem. 

Yes, it was static:
public static IMobileServiceSyncTable<Message> MessagesRepo;
But how does it effect? Should we not use static Repositories?

I was also using this method for saving the object. Also, there were some cases were in a new item with Id set was saved using this. Can this lead to any issues? I have now removed this and added seperate functions for Insert and Update.

    public virtual async Task<bool> SaveItemAsync (T item)
		{
            try
            {
                if (item.Id == null)
                {
                    await syncTable.InsertAsync(item);
                }
                else
                {
                    await syncTable.UpdateAsync(item);
                }

                await this.client.SyncContext.PushAsync();
                return true;
            }
            catch (MobileServiceInvalidOperationException msioe)
            {
                Debug.WriteLine("Sync<{0}> SaveItemAsync EXCEPTION TYPE: {1}, EXCEPTION:{2}", typeof(T).ToString(), msioe.GetType().ToString(), msioe.ToString());
            }
            catch (Exception e)
            {
                Debug.WriteLine("Sync<{0}> SaveItemAsync EXCEPTION TYPE: {1}, EXCEPTION:{2}", typeof(T).ToString(), e.GetType().ToString(), e.ToString());
            }
            return false;
		}

**Comment by iitr-ankur** [comment] 2015-08-14 14:02
Ping, any update on this?

**Comment by phvannor** [comment] 2016-01-11 17:41
We did find a threading issue last week that could be the root cause here, @fabiocav can you comment?

**Comment by phvannor** [comment] 2016-01-11 17:43
A little longer ago then I thought: commit to Mobile Apps branch here: https://github.com/Azure/azure-mobile-apps-net-client/commit/a91a0956664e4c7e44c2d7975dc79c9522e02c72

Are you using the Services or Apps SDK these days?  Looks like the newest Apps (2.0.1) may contain this fix.

**Comment by fabiocav** [comment] 2016-01-11 17:59
Indeed, this seems to be related to the issue we found, which has been fixed on 2.0.1.

**Comment by paulbatum** [comment] 2016-01-11 21:31
Closing as this is fixed in the latest version of our SDK. If it continues to reproduce for you on the new SDK, please file a new issue at https://github.com/Azure/azure-mobile-apps-net-client. If its critical that you get a fix for this issue for the mobile services SDK, please reopen this issue.

**Closed by paulbatum** 2016-01-11 21:31 UTC
Labels: Area-Managed, Resolution-Fixed
