### ISSUE TITLE
[JavaScript] Suggestion - use Grunt for building the HTML/JS SDK

### ISSUE THREAD

**Issue by joewood** [Azure/azure-mobile-services#319] opened 2014-07-18 16:47 UTC
The build process for JavaScript is dependent on Visual Studio and focused Windows 8 store development. To better support regular HTML/JS development I would suggest adopting more widely adopted web based tools - such as Grunt.

Additionally, consider distributing the client SDK over bower and npm.

**Comment by paulbatum** [comment] 2016-01-13 00:39
Dupe of https://github.com/Azure/azure-mobile-apps-js-client/issues/47

**Closed by paulbatum** 2016-01-13 00:39 UTC
Labels: Resolution-Duplicate
