### ISSUE TITLE
Getting exception while fetching data from Azure Mobile service on Windows Phone 8.1

### ISSUE THREAD

**Issue by hemlata09** [Azure/azure-mobile-services#616] opened 2015-03-09 12:06 UTC
I was facing issue (MissingManifestResource_NoPRIresources) with my app in Release mode so  I have updated Mobile Service SDK 1.3.1 and SQLiteStore 1.0.1 then its working fine in release mode. After that I deployed on App store with updated dlls but its throwing same exception (MissingManifestResource_NoPRIresources) after installing on Windows Phone.
![image](https://cloud.githubusercontent.com/assets/4252253/6554503/8d97d940-c682-11e4-9d94-3b0b8a793738.png)

I logged this exception then found this exception occurred while pull data from Azure Mobile Services. Please see below exception:
System.Resources.MissingManifestResourceException: [MissingManifestResource_NoPRIresources]
Arguments: 
Debugging resource strings are unavailable. Often the key and arguments provide sufficient information to diagnose the problem. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30227.0&File=mscorlib.dll&Key=MissingManifestResource_NoPRIresources
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.WindowsAzure.MobileServices.Resources.get_ODataExpressionParser_OpenParenExpected()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseParenExpression()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParsePrimaryStart()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParsePrimary()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseUnary()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseMultiplicative()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseAdditive()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseComparison()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseLogicalAnd()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseLogicalOr()
   at Microsoft.WindowsAzure.MobileServices.Query.ODataExpressionParser.ParseFilter()
   at Microsoft.WindowsAzure.MobileServices.Query.MobileServiceTableQueryDescription.Parse(String tableName, String query, String uriPath)
   at Microsoft.WindowsAzure.MobileServices.Query.MobileServiceTableQueryDescription.Parse(Uri applicationUri, String tableName, String query)
   at Microsoft.WindowsAzure.MobileServices.Sync.MobileServiceSyncContext.<PullAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at JJFood.Helpers.SyncHelper.<DownloadRouteData>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at JJFood.ViewModel.LoginViewModel.<VerifyPin>d__10.MoveNext()

Its very urgent. Please suggest solution and any work around.
Thanks,
Hema

**Comment by phvannor** [comment] 2015-03-09 23:31
The error you are seeing is a bug with the locale not being present in our PRI file, and it not falling back to the defaults.  We expect this issue is hiding an actual error in your code.  

The actual error should be:

"'(' expected."
https://github.com/Azure/azure-mobile-services/blob/master/sdk/Managed/src/Microsoft.WindowsAzure.MobileServices/Resources.resx#L327

Can you capture the query you are passing in and add it here?  Is there something about the way you make it that differs between your working & crashing cases?

**Comment by hemlata09** [comment] 2015-03-10 05:51
Thanks for your reply.
We are using below query to pull data from Azure Mobile Services:
var routeSyncTable = App.MobileService.GetSyncTable<Route>();
var routeQuery = routeSyncTable.Where(e => e.RouteId == routeId);
 await routeSyncTable.PullAsync(null, routeQuery);

For await routeSyncTable.PullAsync(null, routeQuery); line we are getting this error.
I think there is problem with passing null as queryId. 

Can you please provide solution on that.

Thanks,
Hema

**Comment by hemlata09** [comment] 2015-03-10 09:22
i think offline sync is not working. When I create a release build and call await SyncContext.PushAsync() it never returns back to the context.

I dont really know what is happening,

Code:
 await App.MobileService.SyncContext.PushAsync();
 return true;

When I run a debug build everything works fine.

I can't understand, whats happening in Release mode?

Its a very urgent. Please provide a quick solution or setup a call with me.

Thanks,
Hema

**Comment by phvannor** [comment] 2015-03-10 23:22
No QueryId will do a full pull each time you call Pull(), I'm not sure why you would get the original error you showed.  Can routeId have any special characters in it (', ", (, ), etc)?

For Push(), we'd probably need more context, asking on stackoverflow or to mobileservices@microsoft.com would go faster and perhaps including some additional context on where/when you are calling this.  I'm not sure what the difference would be for debug/release.  Is the workflow identical?  Is your delegate being called?  Push does wait on previous sync ops, so if you called pull (and its still running/it crashed) that could be the root cause.

**Comment by paulbatum** [comment] 2015-12-08 19:55
This is fixed now.

**Closed by paulbatum** 2015-12-08 19:55 UTC
Labels: Managed
