### ISSUE TITLE
ThrowOutOfMemory Error in MobileServiceList object

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-services#721] opened 2015-06-08 11:57 UTC
In my android app, I am querying the Local Sqlite DB, to fetch me a list of 30.000 records and
I get a ThrowOutOfMemory error for the MobileServiceList object that holds the results of the query. 
Also the read() procedure from the DB takes too long.

**Comment by marianosz** [comment] 2015-07-07 18:02
Hi @icsd.

I performed the following steps in order to reproduce the issue,
 
1- Inserted 30000 records in a local table with the following custom class definition:
String id;
String mName;
int mAge;
double mFloatingNumber;
Date mDate;
boolean mFlag;
 
2 - I ran several combination of queries on the records and stored it in MobileServiceList object.
 
However I did not run into OutOfMemory exception.
 
Can you provide me the definition of the class and query results to help me reproduce the issue?

**Comment by icsd** [comment] 2015-08-02 12:39
Hi @marianosz 

The objects that i use are bigger than the one in your example. They contain about 25 instance variables. The error occured in very simple queries like read().

**Comment by ysxu** [comment] 2015-12-16 01:14
@icsd We generally would recommend against storing large amounts of data in Local Sqlite DB. What is the scenario that would require all data to be in stored locally?

**Comment by paulbatum** [comment] 2015-12-30 21:56
@icsd closing for now since we cannot reproduce. If you get a good set of repro steps for us to follow, please file a new issue against the new repo for our Android SDK: https://github.com/azure/azure-mobile-apps-android-client

**Closed by paulbatum** 2015-12-30 21:56 UTC
Labels: Area-Android, Resolution-Not Reproducible
