### ISSUE TITLE
Android SDK depends on deprecated AndroidHttpClient class

### ISSUE THREAD

**Issue by rothschild86** [Azure/azure-mobile-services#776] opened 2015-08-19 23:22 UTC
As of couple of days ago, azure mobile services can no longer be used in projects that also use (or migrate to) Android's latest App Compat library, which is in, I assume. a large portion of projects out there. Reason: v23 requires compiling against sdk-23, which removes AndroidHttpClient code entirely.

**Comment by soninaren** [comment] 2015-08-20 18:27
@rothschild86 Thank you for bringing this to our attention. We are investigating this.

**Comment by rothschild86** [comment] 2015-08-27 17:36
As of today, still cannot successfully build against the new sdk with proguard enabled. Maybe some insight on your end?

The main culprit seems to be com.microsoft.windowsazure.mobileservices.http.HttpPatch....

http://stackoverflow.com/questions/32160170/how-to-make-org-apache-http-legacy-work-with-proguard-azure-mobile-services

**Comment by phvannor** [comment] 2015-08-31 16:11
@rothschild86 let me check what the status is on our side

**Comment by soninaren** [comment] 2015-08-31 23:29
@rothschild86 
The AndroidHttpClient class was deprecated from API level 22 and removed in API Level 23. This would cause compile errors for the client trying to use AndroidHttpClient class with compileSdkVersion 23. However the same app should be able to compile and run the app with 'com.microsoft.azure:azure-mobile-services-android-sdk:2.0.3' as a dependency without any issues. The configuration below demonstarates the same behaviour. I would recommend using Android Studio for this.

Here is the complete code of a client app using the above configuration.
https://github.com/soninaren/AndroidSample/tree/master/XamTest

I was unable to reproduce the issue with this configuration.

Test devices
Nexus 6 (API Level 23) emulator
Actual device (API Level 21)


Gradle Configuration
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.0'
    defaultConfig {
        applicationId "com.example.zumoappname"
        minSdkVersion 11
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    repositories {
        flatDir {
            dirs 'aars'
        }
    }
    productFlavors {
    }
}

dependencies {
    compile 'com.google.code.gson:gson:2.3'
    compile 'com.google.guava:guava:18.0'
    compile 'com.microsoft.azure:azure-mobile-services-android-sdk:2.0.3'
    compile 'com.microsoft.azure:azure-notifications-handler:1.0.1@jar'
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
}

**Comment by rothschild86** [comment] 2015-09-01 00:02
Thank you for testing this.

That has been my experience as well, with the only exception that once Service Filters are introduced, even simple lines such as 

                    final MobileServiceException mEx = (MobileServiceException) e.getCause();
                    int responseCode = mEx.getResponse().getStatus().getStatusCode();

no longer work (class not found, etc). From there we are back to including org.apache.http.legacy jar and back to stub/abstract errors... (http://stackoverflow.com/questions/32160170/how-to-make-org-apache-http-legacy-work-with-proguard-azure-mobile-services/32303296#32303296)

**Comment by soninaren** [comment] 2015-09-02 00:38
I see, the SDK directly returns the objects from org.apache.http causing compile errors. We are looking into replacing the deprecated classes. In the meantime you can download the jar files from the links below and compile the project successfully. I have updated the sample GitHub client code to use the jar files and service filter.

Apache download page
http://hc.apache.org/downloads.cgi?Preferred=http%3A%2F%2Fwww.us.apache.org%2Fdist%2F
Zip containing the jar files
http://www.us.apache.org/dist//httpcomponents/httpclient/binary/httpcomponents-client-4.5-bin.zip

Also you will have to add the following to gradle configuration for the jar files to work

```
android {
 packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
}
```

**Comment by rothschild86** [comment] 2015-09-04 17:39
Thank you for being responsive to this issue. OkHttp appears to be a defacto replacement for the http client.

**Comment by PrakashJ12** [comment] 2015-09-25 16:02
Is there any progress on this issue?

**Comment by soninaren** [comment] 2015-09-25 21:14
This is on our backlog to fix, but we don't have a timeline to share yet. Since there's a workaround, we're focusing on higher-priority items such as support for Mobile Apps. After that, we plan to tackle issues like this one.

**Comment by paulbatum** [comment] 2015-12-08 19:32
I see the fix for this was merged into mobileapp branch - should be fixed in next android sdk release for mobile apps.

**Closed by paulbatum** 2015-12-08 19:32 UTC
Labels: Android

**Comment by rothschild86** [comment] 2015-12-08 19:50
awesome!
