### ISSUE TITLE
Installing v 1.0.4

### ISSUE THREAD

**Issue by DominikErnst** [Azure/azure-mobile-services#849] opened 2015-11-13 08:04 UTC
PM> Install-Package WindowsAzure.MobileServices.SQLiteStore -Version 1.0.4 
Attempting to gather dependencies information for package 'WindowsAzure.MobileServices.SQLiteStore.1.0.4' with respect to project ???\???.Windows', targeting 'Windows,Version=v8.1'
Attempting to resolve dependencies for package 'WindowsAzure.MobileServices.SQLiteStore.1.0.4' with DependencyBehavior 'Lowest'
Install-Package : Unable to find a version of 'Microsoft.Bcl' that is compatible with 'WindowsAzure.MobileServices 2.0.0-beta-2 constraint: Microsoft.Bcl (≥ 1.1.9)', 'WindowsAzure.MobileServices.SQLiteStore 1.0.4 constraint: 
Microsoft.Bcl (≥ 1.1.9)'.
At line:1 char:1
+ Install-Package WindowsAzure.MobileServices.SQLiteStore -Version 1.0. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by phvannor** [comment] 2015-11-13 17:50
If you are using WindowsAzure.MobileServices 2.0.0-beta-2 then you need to use the https://www.nuget.org/packages/WindowsAzure.MobileServices.SQLiteStore/2.0.0-beta for SQLiteStore.

**Comment by DominikErnst** [comment] 2015-11-17 06:50
Thanks, but really BETA? Hope there is a stable version soon.

**Comment by phvannor** [comment] 2015-11-17 17:08
Mobile Services is not in beta, for that you need to use 1.3.2 of Mobile Services (https://www.nuget.org/packages/WindowsAzure.MobileServices/1.3.2) and then you can use 1.0.4 of SQLiteStore.

The 2.0-beta* are intended for the new Mobile Apps setup (which is in preview)  GA for Mobile Apps is coming at the end of the month.

**Comment by DominikErnst** [comment] 2015-11-19 08:37
I had to install SQLiteStore 1.0.98.1, because of compatibility reasons. It is installed but I have to test it now...

**Comment by phvannor** [comment] 2015-11-19 16:35
1.0.98.1 of what package?  

1.0.4 of SQLiteStore should take SQLitePCL which is at 3.8.7.2 (https://www.nuget.org/packages/SQLitePCL/), and the newest SQLite base release looks like 3.9.2.  

@gb92 can you note what version of SQLite you tested with for the last release?

**Comment by DominikErnst** [comment] 2015-11-21 08:50
I used this 

https://www.nuget.org/packages/System.Data.SQLite/

**Comment by DominikErnst** [comment] 2015-11-21 09:11
When i download the sample application from portal.azure, these packages are used
<packages>
  <package id="Microsoft.Bcl" version="1.1.9" targetFramework="wpa81" />
  <package id="Microsoft.Bcl.Build" version="1.0.14" targetFramework="wpa81" />
  <package id="Microsoft.Net.Http" version="2.2.28" targetFramework="wpa81" />
  <package id="Newtonsoft.Json" version="6.0.4" targetFramework="wpa81" />
  <package id="WindowsAzure.MobileServices" version="2.0.0-beta-3" targetFramework="wpa81" />
</packages>

**Comment by DominikErnst** [comment] 2015-11-21 09:14
I found that the sample Application i can download from portal.azure are made for Windows 8.1, so there are legazy, hope that MS updates the generated Apps to Windows 10 Apps, soon.

**Comment by phvannor** [comment] 2015-11-21 17:32
@adrianhall can you provide a link to your Win10 updates here?  And let Dominik know what vpackages/version(s) you are using?

**Comment by adrianhall** [comment] 2015-11-30 18:28
My quickstart example is here: https://github.com/adrianhall/quickstarts/tree/master/QuickStart.UWP 

The dependencies are using the latest release as of check-in.

    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "WindowsAzure.MobileServices": "2.0.0-beta-3",
    "WindowsAzure.MobileServices.SQLiteStore": "2.0.0-beta-2"

I'm going to upgrade the packages to the GA packages as soon as they go live.  I don't expect them to be functionally different though.

**Comment by adrianhall** [comment] 2015-12-01 20:45
Update: I've just updated my quickstart project to install the latest packages from NuGet.  Check out the repository for the new packages.

**Comment by DominikErnst** [comment] 2015-12-03 07:11
Thank you, but  .... :-(

Old Version: 
Could not find SDK "SQLite.UAP.2015, Version=3.9.2".	 QuickStart.UWP			

Latest Version:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	QuickStart.UWP	C:\Users\Dominik Ernst\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs	2	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	QuickStart.UWP	C:\Users\Dominik Ernst\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs	3	Active
Error	CS0400	The type or namespace name 'System' could not be found in the global namespace (are you missing an assembly reference?)	QuickStart.UWP	C:\Users\Dominik Ernst\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	QuickStart.UWP	C:\Users\Dominik Ernst\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS0246	The type or namespace name 'FrameworkDisplayName' could not be found (are you missing a using directive or an assembly reference?)	QuickStart.UWP	C:\Users\Dominik Ernst\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS0518	Predefined type 'System.String' is not defined or imported	QuickStart.UWP	C:\Users\Dominik Ernst\AppData\Local\Temp\.NETCore,Version=v5.0.AssemblyAttributes.cs	4	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	QuickStart.UWP	D:\Users\Dominik Ernst\Projects\Samples\quickstarts-master\QuickStart.UWP\App.xaml.cs	1	Active
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	QuickStart.UWP	D:\Users\Dominik Ernst\Projects\Samples\quickstarts-master\QuickStart.UWP\App.xaml.cs	1	Active
Error	CS0012	The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.	QuickStart.UWP	D:\Users\Dominik Ernst\Projects\Samples\quickstarts-master\QuickStart.UWP\App.xaml.cs	13	Active

**Comment by adrianhall** [comment] 2015-12-06 14:14
Hey Dominik,

I've run into this problem a couple of times when cloning a project.  VS doesn't seem to want to add System automatically when restoring packages.  Check to ensure the system assemblies are added to the project.

**Comment by DominikErnst** [comment] 2015-12-06 15:33
There is no way to reference to a system assembly.
In your Sample Code I have a "Universal Windows" Reference, the Path leads to "C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\1.0.0.0\", version 10.0.10240.0
when I change the Target Version to 10.0.10586.0 the Path leads to "C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.CallsVoipContract\1.0.0.0\"
The Reference to "SQLite for Universal App Platform" is with a little yellow exclamation point. What I have to install here?
Visual Studio 2015 Update 1 is so full of BUGs. It's soooo frustrating! I develop .NET Applications since 2002, VS 2015 is Garbage, I never had a Version of VS, that is so bad. :-(
I never would use it in my business. It's not usable for production.

**Comment by paulbatum** [comment] 2015-12-29 23:07
Hey @DominikErnst,

I just ran through this scenario myself and I couldn't reproduce the problems you're encountering. Here are the steps I followed:

1. Install Sqlite for UWP:
  * https://visualstudiogallery.msdn.microsoft.com/4913e7d5-96c9-4dde-a1a1-69820d615936
2. Create new blank UWP app
3. Add the following NuGet references:
  * https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client/2.0.1/
  * https://www.nuget.org/packages/Microsoft.Azure.Mobile.Client.SQLiteStore/2.0.1
4. Right click on project, Add->Reference. Select:
  * Univeral Windows -> Extensions -> SQLite for Universal App Platform 3.9.2
  * Univeral Windows -> Extensions -> Visual C++ 2015 Runtime For UWP 14.0
5. Build, confirm project compiles without any errors
6. Go to MainPage.xaml.cs and add:

        private static MobileServiceClient MobileService = new MobileServiceClient("https://mobileappga.azurewebsites.net");

        protected async override void OnNavigatedTo(NavigationEventArgs e)
        {
            base.OnNavigatedTo(e);
            await InitLocalStoreAsync();
            var dialog = new MessageDialog("Done");
            await dialog.ShowAsync();
        }

        private async Task InitLocalStoreAsync()
        {
            if (!MobileService.SyncContext.IsInitialized)
            {
                var store = new MobileServiceSQLiteStore("localstore.db");
                store.DefineTable<TodoItem>();
                await MobileService.SyncContext.InitializeAsync(store);
            }            
        }

        public class TodoItem
        {
            public string Id { get; set; }
            public string Text { get; set; }
            public bool Complete { get; set; }
        }

7. Add necessary usings:
```
using Microsoft.WindowsAzure.MobileServices;
using Microsoft.WindowsAzure.MobileServices.SQLiteStore;
using System.Threading.Tasks;
using Windows.UI.Popups;
```

Finally, run the app and confirm that the sqlite store is initialized without error. Please let me know whether these steps work for you.

**Comment by paulbatum** [comment] 2016-01-08 23:32
Closing as answered, please let us know if you run into problems with the above steps.

**Closed by paulbatum** 2016-01-08 23:32 UTC
Labels: Area-Managed, Question, Resolution-Answered
