### ISSUE TITLE
I can not run APK on any device with Azure mobile services android sdk with proguard

### ISSUE THREAD

**Issue by alaa001** [Azure/azure-mobile-services#836] opened 2015-10-31 20:52 UTC
My problem was 64K limit in DEX, and as anyone faced that problem there are two solutions.

1-Use proguard with minifyEnabled true (Recommended).

2-Use multidex enable and of course deal with all considerations and limitations that can happen on runtime.

Anyway I managed to remove most libraries and added each one of them again with proguard config and test.

it kept working Until I added Azure mobile services which is required to use GCM using Azure Service bus.

The app compile and build, but it never runs on any devices.

For Galaxy S3 it shows: INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION

for Sony it shows something related to certificate

I searched a lot and I tried to build and run with a signed Key, but again it builds with no error but it will not run on any device.

This only happen when I user Azure mobile services library.

Note:I am using Azure Mobile services Android SDK: Version 2.0.3

Any help will be appreciated.Thanks in advance.

**Comment by alaa001** [comment] 2015-10-31 20:53
I posted this on stackoverflow
http://stackoverflow.com/questions/33454445/i-can-not-run-apk-on-any-device-with-azure-mobile-services-android-sdk-with-prog

**Comment by ysxu** [comment] 2015-12-16 01:06
@alaa001 Are you still experiencing this issue? We could not reproduce the error and was wondering if you've resolved it.

**Comment by alaa001** [comment] 2015-12-16 01:58
Hi and thanks for the reply , Yes, I still can not register my gcm token through the android client, because the lib will not build with proguard applied, so I had to send the token through api call and manage to register it on server with C# lib to Azure.

An other way to ask my question , can you run the azure mobile services android client lib with progaurd? 

Thanks again

**Comment by mamaso** [comment] 2016-01-11 22:27
Hi @alaa001, 

I've tested proguard with minifyEnabled for the mobile services android quickstart with sdk version 2.0.3.  I am able to build the apk and install it on a Galaxy S5 as well as the visual studio emulator and everything functions as expected.

Unfortunately I can't give you an easy answer as to why you are unable to use proguard with your app.  I'd recommend trying to build and install our quickstart with proguard as a sanity check (https://azure.microsoft.com/en-us/documentation/articles/mobile-services-android-get-started/)

**Comment by paulbatum** [comment] 2016-01-12 18:58
Closing as no repro. Please go ahead and reactivate this issue if you have more specific repro steps for the proguard issue.

**Closed by paulbatum** 2016-01-12 18:58 UTC
Labels: Area-Android, Resolution-Not Reproducible
